# NumPy Exercise

In [1]:

import numpy as np
    

### 1. Array creation and basic operations

In [2]:
# (1) Create a 10x10 random array with values between 0 and 100 (int)

# [0, 101) because the upper bound is exclusive
arr = np.random.randint(0, 101, size = (10, 10))

print(arr)

[[ 63  10  97   9  64  36  96  51  12  44]
 [ 26   9  36  39  15   3  67   1  78  60]
 [  8  15  30  39  12  50  63  59  77  24]
 [ 17  78  39  30  66  12  93  28  94  65]
 [ 50  36 100  73  49   4  17  38  58  27]
 [ 60  82  78  47  85   1  89  80  46  34]
 [ 66  86  17  79  33  39  50  47  55  73]
 [ 37  82  29 100  57  59  67  26  42  82]
 [ 65  36  78  24  35  86  36  89  68  97]
 [ 88  28  76  47  95  17  83  62  74  68]]


In [3]:
# (2) Calculate the minimum, maximum, and mean of the array

min_value = np.min(arr) # Minimum value
max_value = np.max(arr) # Maximum value

# the mean value is calculated by summing up
# all the elements in the array
# and dividing by the total number of elements.
mean_value = np.mean(arr) # Mean value

print("Min:", min_value, "Max:", max_value, "Mean:", mean_value)

Min: 1 Max: 100 Mean: 51.47


In [4]:
# (2) Calculate the minimum, maximum, and mean of the array

min_value = np.min(arr) # Minimum value
max_value = np.max(arr) # Maximum value

# the mean value is calculated by summing up
# all the elements in the array
# and dividing by the total number of elements.
mean_value = np.mean(arr) # Mean value

print("Min:", min_value, "Max:", max_value, "Mean:", mean_value)

Min: 1 Max: 100 Mean: 51.47


### 2. Array reshaping and merging

In [5]:
# (1) Reshape the array into a 5x20 array

# the total number of the elements in the reshaped array
# must be the same as the original array
reshaped_array = arr.reshape(5, 20)

print("Reshaped array:", reshaped_array)

Reshaped array: [[ 63  10  97   9  64  36  96  51  12  44  26   9  36  39  15   3  67   1
   78  60]
 [  8  15  30  39  12  50  63  59  77  24  17  78  39  30  66  12  93  28
   94  65]
 [ 50  36 100  73  49   4  17  38  58  27  60  82  78  47  85   1  89  80
   46  34]
 [ 66  86  17  79  33  39  50  47  55  73  37  82  29 100  57  59  67  26
   42  82]
 [ 65  36  78  24  35  86  36  89  68  97  88  28  76  47  95  17  83  62
   74  68]]


In [6]:
# (2) Create a 1x20 array using np.ones, and concatenate it to the reshaped array along the rows

# the new array has 1 row & 20 columns, with all the values being 1
new_array = np.ones((1, 20))

# reshaped_array: (5, 20)
# new_array: (1, 20)
# concatenated_array: (6, 20)
# axis=0 means "moving along the rows"
# requirement: the number of columns in the two arrays must be consistent
concatenated_array = np.concatenate([reshaped_array, new_array], axis=0)

print("Concatenated array:", concatenated_array)

Concatenated array: [[ 63.  10.  97.   9.  64.  36.  96.  51.  12.  44.  26.   9.  36.  39.
   15.   3.  67.   1.  78.  60.]
 [  8.  15.  30.  39.  12.  50.  63.  59.  77.  24.  17.  78.  39.  30.
   66.  12.  93.  28.  94.  65.]
 [ 50.  36. 100.  73.  49.   4.  17.  38.  58.  27.  60.  82.  78.  47.
   85.   1.  89.  80.  46.  34.]
 [ 66.  86.  17.  79.  33.  39.  50.  47.  55.  73.  37.  82.  29. 100.
   57.  59.  67.  26.  42.  82.]
 [ 65.  36.  78.  24.  35.  86.  36.  89.  68.  97.  88.  28.  76.  47.
   95.  17.  83.  62.  74.  68.]
 [  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
    1.   1.   1.   1.   1.   1.]]


### 3. Logical operations and filtering

In [7]:
# (1) Use boolean indexing to find all elements greater than 50, and set them to 50

# np.where(condition, value_if_true, value_if_false)
# condition is true -> value = value_if_true
# condition is false -> value = value_if_false
# arr means every element in the array
arr = np.where(arr > 50, 50, arr)

print("Array after setting elements > 50 to 50:", arr)

Array after setting elements > 50 to 50: [[50 10 50  9 50 36 50 50 12 44]
 [26  9 36 39 15  3 50  1 50 50]
 [ 8 15 30 39 12 50 50 50 50 24]
 [17 50 39 30 50 12 50 28 50 50]
 [50 36 50 50 49  4 17 38 50 27]
 [50 50 50 47 50  1 50 50 46 34]
 [50 50 17 50 33 39 50 47 50 50]
 [37 50 29 50 50 50 50 26 42 50]
 [50 36 50 24 35 50 36 50 50 50]
 [50 28 50 47 50 17 50 50 50 50]]


In [8]:
# (1) Use boolean indexing to find all elements greater than 50, and set them to 50

# np.where(condition, value_if_true, value_if_false)
# condition is true -> value = value_if_true
# condition is false -> value = value_if_false
# arr means every element in the array
arr = np.where(arr > 50, 50, arr)

print("Array after setting elements > 50 to 50:", arr)

Array after setting elements > 50 to 50: [[50 10 50  9 50 36 50 50 12 44]
 [26  9 36 39 15  3 50  1 50 50]
 [ 8 15 30 39 12 50 50 50 50 24]
 [17 50 39 30 50 12 50 28 50 50]
 [50 36 50 50 49  4 17 38 50 27]
 [50 50 50 47 50  1 50 50 46 34]
 [50 50 17 50 33 39 50 47 50 50]
 [37 50 29 50 50 50 50 26 42 50]
 [50 36 50 24 35 50 36 50 50 50]
 [50 28 50 47 50 17 50 50 50 50]]


### 4. Linear algebra operations

In [9]:
# (1) Create a 3x3 identity matrix

# identity matrix: a square matrix with 1s on the main diagonal and 0s elsewhere
identity_matrix = np.eye(3)
print("Identity matrix:", identity_matrix)

Identity matrix: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# (2) Create a 3x3 random matrix and compute its inverse

# np is the defined alias for the numpy library
# random is the module in numpy
# rand is the function in the "random" module
random_matrix = np.random.rand(3, 3)

# linalg refers to "linear algebra"
inv_matrix = np.linalg.inv(random_matrix) # Inverse of the matrix

print("Random matrix:", random_matrix)
print("Inverse matrix:", inv_matrix)

Random matrix: [[0.248069   0.53166778 0.85881526]
 [0.00978828 0.17418704 0.06519455]
 [0.76421792 0.95299215 0.59645729]]
Inverse matrix: [[-0.5755499  -6.90858593  1.58384044]
 [-0.60613335  7.00549612  0.10702597]
 [ 1.70588218 -2.34135397 -0.52374939]]


In [11]:
# (3) Matrix multiplication

# np.dot(random_matrix, inv_matrix) is also valid in this case
# but the "@" operator is more concise and easier to read for matrix multiplication
matrix_product = random_matrix @ inv_matrix

print("Matrix product (should be close to identity matrix):", matrix_product)

Matrix product (should be close to identity matrix): [[ 1.00000000e+00 -3.95480813e-16  2.95342455e-17]
 [ 4.03618501e-17  1.00000000e+00 -2.00212388e-17]
 [ 8.05801507e-17 -3.36688897e-16  1.00000000e+00]]
